### ISSUE TITLE
Cannot download the Jester dataset

### ISSUE THREAD

**Issue by daveajstearns** [learn-co-curriculum/dsc-implementing-recommender-systems#2] opened 2020-04-23 12:30 UTC
I am receiving a 404 error upon running the download cell. I have already installed `surprise` and imported it.

UPDATE: Also tried to refresh the page after installing the library, and then reimported. Still cannot install.

**Comment by jessepisel** [comment] 2022-12-27 22:52
Thanks for opening this issue @daveajstearns :wave:. I am not able to reproduce this issue on my local machine. For those that come after you and run into this issue, you can download the dataset from from [this link](https://eigentaste.berkeley.edu/dataset/archive/jester_dataset_2.zip) in your browser and move it into the root of this repository. More information on the dataset is found at https://eigentaste.berkeley.edu/dataset/archive/.

I am closing this issue at this time.

**Closed as completed by jessepisel** 2022-12-27 22:52 UTC
